spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}

  main:
    allow-bean-definition-overriding: true

jwt:
  secret-key: ${JWT_SECRET:cheajib-server-secret-key}
  access-exp: ${JWT_ACCESS_EXP":1209600}
  refresh-exp: ${JWT_REFRESH_EXP:1209600}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer }

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION:ap-northeast-2}
    stack:
      auto: false


auth:
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    state: ${NAVER_STATE}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
